### ISSUE TITLE
where is dependent option?

### ISSUE THREAD

**Issue by kiosan** [RubyForceTeam/cookbook#44]
https://github.com/RubyForceTeam/cookbook/blob/1b0d3b037cf46253f83036a12ad864e597b6bfa8/app/models/recipe.rb#L7

**Comment by illia108** [comment]
Right here https://github.com/RubyForceTeam/cookbook/blob/1c7641709c30abb7f1f913c495357ec50aa8cdbc/app/models/rating.rb#L4

**Comment by illia108** [comment]
Fixed with this PR https://github.com/RubyForceTeam/cookbook/pull/47/files
