### ISSUE TITLE
we may need one more field as "comment"

### ISSUE THREAD

**Issue by kiosan** [RubyForceTeam/cookbook#51]
https://github.com/RubyForceTeam/cookbook/blob/5f9d69b279e58aae8e0710497091e1d0100fe5be/db/schema.rb#L37

for example, when we want to add:

пів чайної ложки солі

**Comment by BogdanLinnik** [comment]
we have unit`s to specify measuring for specific ingredient. In this case when user choose some ingredient we can show in which unit he can mesure this. For additional information about recipe we have "description" field in Recipe class
