### ISSUE TITLE
all rating logic should be in corresponding class, recipe for example

### ISSUE THREAD

**Issue by kiosan** [RubyForceTeam/cookbook#57]
https://github.com/RubyForceTeam/cookbook/blob/5f9d69b279e58aae8e0710497091e1d0100fe5be/app/controllers/admin/recipes_controller.rb#L18

**Comment by BogdanLinnik** [comment]
We have Rating class. Can it be there?

**Comment by BogdanLinnik** [comment]
I moved ratings values into constant RATING_RANGE in Rating class

**Comment by kiosan** [comment]
create PR to review

**Comment by BogdanLinnik** [comment]
Created
