### ISSUE TITLE
not the best idea to paginate recipes on user's page. better to have recipes page with ability to filter by user

### ISSUE THREAD

**Issue by kiosan** [RubyForceTeam/cookbook#58]
https://github.com/RubyForceTeam/cookbook/blob/5f9d69b279e58aae8e0710497091e1d0100fe5be/app/controllers/admin/users_controller.rb#L9

**Comment by BogdanLinnik** [comment]
Pages ingredients, subcategories, users and categories has their own pages were we can see their recipes. Shoud we change this on sorting on recipes page like for users too?

**Comment by BogdanLinnik** [comment]
Fixed for all pages
